package com.minelife.gangs;

public enum GangPermission {

    DEPOSIT_MONEY, JOIN_FIGHTS, TELEPORT_HOME, REGROUP, INVITE, SETHOME_DELHOME, TOGGLE_FRIENDLY_FIRE, LEVEL_UP, CHALLENGE, ACCEPT_CHALLENGES, WITHDRAW_MONEY, MANAGE_ALLIANCES, KICK_MEMBERS, PROMOTE_AND_DEMOTE, OPEN_LOCKS

}
